name: Build Superset PT-BR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔥 evita problema de Node deprecated
      - name: Force Node 24
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      # 🔥 aumenta estabilidade do Docker build
      - name: Build Docker image
        run: docker build -t superset-pt-br . --progress=plain

      - name: Save image
        run: docker save superset-pt-br -o superset-pt-br.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: superset-image
          path: superset-pt-br.tar