name: Build Superset PT-BR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t superset-pt-br .

      - name: Save image
        run: docker save superset-pt-br -o superset-pt-br.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: superset-image
          path: superset-pt-br.tar
